KOD-29.2 Zadanie: rozbudowa testów - pokrycie metod = 80%
piotr-kostka/kodilla-application pull request #28
Opened 2022-09-29 12:09 UTC by piotr-kostka

2022-09-29 12:28 UTC, piotr-kostka commented
Trochę się męczyłem żeby pokrycie metod było na 80% ale udało mi się :)

2022-09-29 14:57 UTC, mps4dev requested changes

2022-09-29 14:57 UTC, mps4dev commented on src/test/java/com/crud/tasks/domain/CreatedTrelloCardDtoTestSuite.java
> +class CreatedTrelloCardDtoTestSuite {
Co to jest??? Jeszcze caly kontekst springa wlaczasz, aby sprawdzic, czy java dziala

2022-09-29 17:43 UTC, mps4dev requested changes

2022-09-29 17:43 UTC, mps4dev commented on src/test/java/com/crud/tasks/config/ConfigTestSuite.java
> +    void getTrelloConfigTest() {
Co tu testujesz? Czy spring dziala? Dziala.

2022-09-30 17:45 UTC, mps4dev approved these changes

2022-09-30 20:06 UTC, merged